[package]
authors = ["kardeiz <kardeiz@gmail.com>"]
build = "build.rs"
name = "ldap"
version = "0.2.0"

[build-dependencies]
bindgen = "0.16.0"

[dependencies]
log = "0.3.5"

[dev-dependencies]
env_logger = "0.3.4"
